project:
  type: book
  output-dir: docs

book:
  title: "DaSL Community Handbook"
  author: "Ted Laderas"
  date: "2/14/2024"
  chapters:
    - index.qmd
    - learning_paths.qmd
    - getting_good_with_the_shell.qmd
    - hpc_for_scientists.qmd
    - wdl_for_you_and_me.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



